services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=easyfarm_spring_database'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=root'
    ports:
      - '5431:5432'
